image: Visual Studio 2022
version: 4.0.0.{build}
clone_folder: c:\projects\nlog
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '4.0.0'  #only change on major releases
  file_version: '{version}'
  package_version: '4.0'
  informational_version: '4.0'
  version: '4.0'
skip_tags: true
skip_branch_with_pr: true
nuget:
  disable_publish_on_pr: true
build_script:	
  - ps: dotnet restore
  - ps: msbuild /t:build,pack /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /verbosity:minimal /p:ContinuousIntegrationBuild=true
test_script:
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"c:\projects\nlog\NLog.Owin.Logging.Tests\bin\Release\net452\NLog.Owin.Logging.Tests.dll"  -returntargetcode -filter:"+[NLog.Owin.Logging]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
 
artifacts:
  - path: '**\NLog.*.nupkg'
  - path: '**\NLog.*.snupkg'
deploy:
- provider: NuGet
  api_key:
    secure: e+0IpLU3V1eXUsWCRjKGuyyeuLQYfFpv6BAoIihFQryuYZsOWVvxUBvQOC0dOL2n
  on:
    branch: master
